version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.1

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build
  deploy:
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - run:
          name: Install netlify-cli
          command: sudo yarn global add netlify-cli
      - run:
          name: Deploy to Netlify
          command: netlify deploy --dir=./public -p

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
